[package]
name = "wup-web"
version = "1.0.0"
edition = "2021"
description = "WhatsApp Web Client"
authors = ["eoliann"]
license = "MIT"
build = "build.rs"

[build-dependencies]
tauri-build = { version = "2.4.1", features = [] }

[dependencies]
tauri = { version = "2.8.5", features = ["tray-icon"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["blocking", "json"] }
semver = "1"
tauri-plugin-dialog = "2.4.0"
tauri-plugin-opener = "2.5.0"
