name: Notify Telegram on Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_CHATS: ${{ secrets.TG_CHATS }}
      RELEASE_NAME: ${{ github.event.release.name || github.repository }}
      RELEASE_TAG:  ${{ github.event.release.tag_name || github.ref_name }}
      RELEASE_URL:  ${{ github.event.release.html_url || format('{0}/{1}/releases', github.server_url, github.repository) }}
      ASSET_URL:   ${{ github.event.release.assets[0].browser_download_url || '' }}

    steps:
      - name: Send Telegram notifications
        run: |
          TEXT="📢 <b>Wup Web (client web WhatsApp) are o nouă versiune pe GitHub!</b>
          <b>${RELEASE_NAME}</b> (tag: <code>${RELEASE_TAG}</code>)
          👉 <a href='${RELEASE_URL}'>Mergi la pagina noii versiuni</a>"

          if [[ -n "${ASSET_URL}" ]]; then
            TEXT="$TEXT
            ⬇️ <a href='${ASSET_URL}'>Descarcă fișierul .exe</a>"
          fi

          IFS=',' read -r -a CHATS <<< "${TG_CHATS}"
          for ITEM in "${CHATS[@]}"; do
            ITEM_TRIM=$(echo "$ITEM" | xargs)
            [[ -z "$ITEM_TRIM" ]] && continue

            if [[ "$ITEM_TRIM" == *":"* ]]; then
              CHAT_ID="${ITEM_TRIM%%:*}"
              THREAD_ID="${ITEM_TRIM##*:}"
              echo ">>> Trimit catre $CHAT_ID in topic $THREAD_ID"
              curl -s "https://api.telegram.org/bot${TG_BOT_TOKEN}/sendMessage" \
                -d chat_id="${CHAT_ID}" \
                -d message_thread_id="${THREAD_ID}" \
                -d parse_mode="HTML" \
                --data-urlencode "text=${TEXT}"
            else
              CHAT_ID="$ITEM_TRIM"
              echo ">>> Trimit catre grup simplu $CHAT_ID"
              curl -s "https://api.telegram.org/bot${TG_BOT_TOKEN}/sendMessage" \
                -d chat_id="${CHAT_ID}" \
                -d parse_mode="HTML" \
                --data-urlencode "text=${TEXT}"
            fi
          done
